### ISSUE TITLE
Distribute fonts with npm package

### ISSUE THREAD

**Issue by avkvirtru** [avkvirtru/virtuoso-design-system#41]
## Description
I'm working in raw HTML. I can quickly drop in our [latest design tokens](https://unpkg.com/virtuoso-design-system@latest/dist/design_tokens.css) with 
```html
  <link 
    rel="stylesheet" 
    href="https://unpkg.com/virtuoso-design-system@latest/dist/design_tokens.css">
```

Which lets me write compliant styles like: 
```css
    body {
      font: var(--vds-font-body); /* normal normal normal normal   1.6rem/ 1.5  "Open Sans", Helvetica, Arial, sans-serif */
    }
```

But `body` won't actually render in Open Sans (from `"Open Sans", Helvetica, Arial, sans-serif`) because the Open Sans files aren't distributed for me to link to…

## Describe the solution you'd like
I want to be able to pull in fonts from our npm package (and unpkg) as easily as design tokens.

## Describe alternatives you've considered
Downloading a copy of https://github.com/virtru/virtru-typography … though we're trying to move away from that repo as a dependency not managed in this repo.
